pipeline:
  build:
    image: plugins/docker
    settings:
      repo: redpencil/frontend-vliz-vocabserver
      tags: ${CI_COMMIT_TAG##v}
    secrets: [ docker_username, docker_password ]
when:
  event: tag
  tag: v*
